<template>


    <div v-if="visible" :class="visible ? 'popup-center' : ''">
        <div class="card" style="width: 36rem;">
            <div class="card-body">
                <h5 class="card-title text-muted">{{ title() }}</h5>
    <!--            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>-->
                <p class="card-text">{{ toolTip() }}</p>
                <a href="#" class="card-link float-end text-info" @click="hideContent">Close</a>
    <!--            <a href="#" class="card-link">Another link</a>-->
            </div>
        </div>
    </div>


<!--    <div v-if="visible" :class="visible ? 'popup-center' : ''" class="border border-1 rounded rounded-xl p-4 z-index-0 bg-gradient-info max-width-500">-->
<!--            <div class="">-->
<!--                <div class="py-2 justify-content-center align-items-center text-center text-white">-->
<!--                    {{ toolTip() }}-->
<!--                </div>-->
<!--                <div>-->
<!--                    <input type="button" class="btn btn-sm btn-info mt-2 mb-0 text-white float-end" @click="hideContent" value="close" />-->
<!--                </div>-->
<!--            </div>-->
<!--    </div>-->
</template>

<script>

export default {
    name: 'showModalContent',

    props: {

    },

    data() {
        return {
            visible: false,

            tag: '',
            tool_tips: {
                //STgradient
                "stgradient_samples": {"title": "Sample selection", "text": "Select the samples to run STgradient"},
                "stgradient_genes": {"title": "Number of most variable genes to use", "text": "Maximum number of genes per sample to test for spatial gradients. The genes to be tested are selected based on standard deviation"},
                "stgradient_annotation_to_test": {"title": "Annotation to test", "text": "The tissue niches to run STgradient. After running STclust (see “Spatial domain detection”), users can choose one of the results generated by that algorithm."},
                "stgradient_reference_cluster": {"title": "Reference cluster", "text": "Select the reference cluster from which spatial gradients are to be tested. The reference cluster could be, for example, a tumor region detected by STclust."},
                "stgradient_clusters_to_exclude": {"title": "Cluster(s) to exclude (optional)", "text": "Optional. Exclude regions/niches from the analysis. By specifying one or more niches, the distances of those spots/cells will not be calculated and will be excluded from the analyses. This option could be useful when removing tissue niches that show necrosis and could add noise to the Spearman’s coefficients."},
                "stgradient_robust_regression": {"title": "Robust regression", "text": "Whether to use robust regression. The functionality is provided by the f.robftest function from the sfsmisc R package. In robust regression, outliers are given less weight towards the calculation of the regression coefficient."},
                "stgradient_ignore_outliers": {"title": "Ignore outliers", "text": "Whether to ignore outliers. This option is automatically disabled if robust regression is selected. If outliers are ignored, traditional linear regression is carried out after removing spots/cells defined as outliers by the interquartile range method. If unchecked, all spots are considered in the analysis."},
                "stgradient_minimum_number_of_neighbors": {"title": "Minimum number of neighbors", "text": "The minimum number of immediate neighbors a reference spot/cell must have to be included in the analysis. This parameter intends to reduce the effect of isolated spots/cells in the calculation of the correlation coefficients. Unsupervised clustering algorithms (such as STclust) can assign niches to isolated spots. Reference spots with less neighbors than specified, will be omitted from the analysis, and hence distances from that spot will not be calculated."},
                "stgradient_restrict_correlation_to_this_limit": {"title": "Restrict correlation to this limit", "text": "A distance value to restrict the correlation analysis. Some tissues can be very heterogeneous in composition. As a result it could be reasonable to test for spatial gradients within a restricted area of the tissue."},
                "stgradient_distance_summary_metric": {"title": "Distance summary metric", "text": "The method to summarize the distances. STgradient calculates the distances each spot/cell to all the spots/cells in the reference niche. A single distance value is calculated for each spot/cell by taking the minimum or average distance. The users are encouraged to try both methods and look for the approach that provides biologically insightful results."},

            },
        }
    },

    mounted() {
        this.emitter.on("show-tooltip", tag => {
            this.showContent(tag);
        });
    },

    methods: {
        showContent(tag) {
            this.tag = tag;
            this.visible = true;
            document.getElementById('_body').classList.add('disabled-clicks');
        },

        hideContent() {
            this.visible = false;
            document.getElementById('_body').classList.remove('disabled-clicks');
        },

        toolTip() {
            return this.tag in this.tool_tips ? this.tool_tips[this.tag].text : '';
        },

        title() {
            return this.tag in this.tool_tips ? this.tool_tips[this.tag].title : '';
        }
    },
}
</script>
