[program:apache2]
command=apache2-foreground
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --queue=default --timeout=259200 --tries=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=%(ENV_WORKER_COUNT)s
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker.log
stopwaitsecs=3600
