<?php

namespace App\Models;

use App\Http\Controllers\spatialContainer;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class Project extends Model
{
    use SoftDeletes;

    protected $table = 'projects';

    protected $fillable = ['name', 'description', 'user_id'];

    protected $appends = ['url', 'project_parameters'];

    private ?spatialContainer $_container = null;

    //Relations
    public function samples(): BelongsToMany
    {
        return $this->belongsToMany(Sample::class);
    }

    public function parameters(): HasMany
    {
        return $this->hasMany(ProjectParameter::class);
    }

    public function genes(): HasMany
    {
        return $this->hasMany(ProjectGene::class);
    }

    //Attributes
    public function getUrlAttribute() {
        return route('open-project', ['project' => $this->id]);
    }

    public function getProjectParametersAttribute() {
        $params = [];
        foreach ($this->parameters as $param)
            $params[$param->parameter] = $param->type === 'number' ? intval($param->value) : $param->value;

        $params['total_genes'] = $this->genes()->count();

        return $params;
    }


    public function getCurrentStepUrl() {
        if($this->current_step === 1)
            return route('import-data', ['project' => $this->id]);

        if($this->current_step === 2)
            return route('qc-data-transformation', ['project' => $this->id]);


        return '/';
    }


    public function createStList() {

        $workingDir = '/users/' . (auth()->id() ?? '9999') . '/' . $this->id . '/';
        $workingDir = str_replace('\\', '/', $workingDir);

        $script = $workingDir . 'STList.R';

        Storage::put($script, $this->getStListScript());

        //Create the initial_stlist
        $this->spatialExecute('Rscript STList.R');

        //Load genes present in samples into the DB
        $genes_file = $workingDir . 'genes.csv';
        if(Storage::fileExists($genes_file)) {
            $data = Storage::read($genes_file);
            $genes = explode("\n", $data);
            $_genes = [];
            foreach ($genes as $gene)
                if(strlen($gene))
                    $_genes[] = ['gene' => $gene, 'project_id' => $this->id];
                //ProjectGene::create(['gene' => $gene, 'project_id' => $this->id]);
            DB::delete('delete from project_genes where project_id=' . $this->id);
            ProjectGene::insert($_genes);
        }

        DB::delete('delete from project_paramaters where project_id=' . $this->id);
        //Load other parameters generated by the R script
        $file = $workingDir . 'max_spot_counts.csv';
        if(Storage::fileExists($file)) {
            $data = trim(Storage::read($file));
            ProjectParameter::insert(['parameter' => 'max_spot_counts', 'type' => 'number', 'value' => $data, 'project_id' => $this->id]);
        }
        $file = $workingDir . 'max_gene_counts.csv';
        if(Storage::fileExists($file)) {
            $data = trim(Storage::read($file));
            ProjectParameter::insert(['parameter' => 'max_gene_counts', 'type' => 'number', 'value' => $data, 'project_id' => $this->id]);
        }

    }

    public function spatialExecute($command) {

        if(is_null($this->_container))
            $this->_container = new spatialContainer($this);

        //dd($this->_container);

        $this->_container->execute($command);

    }






    public function getStListScript() : string {

        $sampleDirs = $this->samples()->pluck('samples.id')->join("/','");
        $sampleDirs = "'" . $sampleDirs . "/'";

        $sampleNames = "'" . $this->samples()->pluck('samples.id')->join("','") . "'";

        $script = "
setwd('/spatialGE')
# Load the package
library('spatialGE')

# Specify paths to directories containing data
count_files = c($sampleDirs)

# Specify sample names
samplenames = c($sampleNames)

# Create STlist
initial_stlist <- STlist(rnacounts=count_files, samples=samplenames)

#Save the STList to disk
save(initial_stlist, file='initial_stlist.RData')

#Obtain gene names in samples and save it in a text file
gene_names = unique(unlist(lapply(initial_stlist@counts, function(i){ genes_tmp = rownames(i) })))
write.table(gene_names, 'genes.csv',sep=',', row.names = FALSE, col.names=FALSE, quote=FALSE)

# Maximum number of counts per spot
max_spot_counts = max(unlist(lapply(initial_stlist@counts, function(i){  max_tmp = max(Matrix::colSums(i)) })))
write.table(max_spot_counts, 'max_spot_counts.csv',sep=',', row.names = FALSE, col.names=FALSE, quote=FALSE)

# Maximum number of counts per gene
max_gene_counts = max(unlist(lapply(initial_stlist@counts, function(i){ max_tmp = max(Matrix::rowSums(i)) })))
write.table(max_gene_counts, 'max_gene_counts.csv',sep=',', row.names = FALSE, col.names=FALSE, quote=FALSE)

";

        return $script;

    }


    public function applyFilter($parameters) {

        $workingDir = '/users/' . (auth()->id() ?? '9999') . '/' . $this->id . '/';
        $workingDir = str_replace('\\', '/', $workingDir);

        $script = $workingDir . 'Filter.R';

        Storage::put($script, $this->getFilterDataScript($parameters));

        $this->spatialExecute('Rscript Filter.R');

    }


    public function getFilterDataScript($parameters) : string {

        $str_params = '';
        foreach ($parameters as $key => $value) {
            $str_params .= strlen($str_params) ? ', ' : '';
            if(strlen($value)) {
                $quote = is_numeric($value) ? '' : "'";
                $str_params .= $key . '=' . $quote . $value . $quote;
            }
        }

        //dd($str_params);

        $script = "
setwd('/spatialGE')
# Load the package
library('spatialGE')

# Load STList from disk
load(file='initial_stlist.RData')

# Apply defined filter to the initial STList
filtered_stlist = filter_data(initial_stlist, $str_params)
save(filtered_stlist, file='filtered_stlist.RData')

#### Plots Filter Data
# Options for plot
filter_meta_options = unique(unlist(lapply(filtered_stlist@spatial_meta, function(i){ max_tmp = grep(paste0(c('libname', 'xpos', 'ypos'), collapse='|'), colnames(i), value=T, invert=T) })))
write.table(filter_meta_options, 'filter_meta_options.csv',sep=',', row.names = FALSE, col.names=FALSE, quote=FALSE)
";

        return $script;

    }



}
