#{HEADER}#

##
# Import to STlist the classifications generated by SpaGCN
#
library('spatialGE')
library('magrittr')

# User arguments:
color_pal = 'smoothrainbow'

load("#{_stlist}#.RData")
stclust_stlist = #{_stlist}#

spagcn_preds = './'
spagcn_preds = list.files(spagcn_preds, pattern='spagcn_predicted_domains_sample_', full.names=T)

samplenames = #{_samples}#

new_cols = c()
for(i in samplenames){
  spagcn_tmp = read.csv(grep(paste0(i, '.csv'), spagcn_preds, value=T))
  new_cols = unique(c(new_cols, colnames(spagcn_tmp)[-1]))
  # Convert domain classifications to factor
  spagcn_tmp[, -1] = lapply(spagcn_tmp[, -1], as.factor)

  # Check for repeated columns in STlist
  duplicated_cols = colnames(stclust_stlist@spatial_meta[[i]])[ colnames(stclust_stlist@spatial_meta[[i]]) %in% colnames(spagcn_tmp[, -1]) ]
  if(length(duplicated_cols) > 0){
    stclust_stlist@spatial_meta[[i]] = stclust_stlist@spatial_meta[[i]][, !(colnames(stclust_stlist@spatial_meta[[i]]) %in% duplicated_cols) ]
  }

  stclust_stlist@spatial_meta[[i]] = stclust_stlist@spatial_meta[[i]] %>%
    dplyr::left_join(., spagcn_tmp, by='libname')
}

# annot_variables used for differential expression and STdiff/STgradient analyses
annot_variables = lapply(names(stclust_stlist@spatial_meta), function(i){
  var_cols=colnames(stclust_stlist@spatial_meta[[i]])[-c(1:5)]
  df_tmp = tibble::tibble()
  for(v in var_cols){
    cluster_values = unique(stclust_stlist@spatial_meta[[i]][[v]])
    df_tmp = dplyr::bind_rows(df_tmp, tibble::tibble(V1=i, V2=v, V3=v, V4=cluster_values, V5=cluster_values))
  }
  return(df_tmp) })
annot_variables = dplyr::bind_rows(annot_variables)

# Check if annot_variables file already exists, then keep annotations from other methods but remove those from SpaGCN that have been modified
if(file.exists('stdiff_annotation_variables_clusters.csv')){
  annot_variables_tmp = data.table::fread('stdiff_annotation_variables_clusters.csv', header=F)
  annot_variables_tmp = annot_variables_tmp[!grepl('^spagcn_k', annot_variables_tmp[['V2']]), ]
  if(nrow(annot_variables_tmp) > 0){
    annot_variables = rbind(annot_variables_tmp, annot_variables)
  }
  rm(annot_variables_tmp) # Clean env
}
write.table(annot_variables, 'stdiff_annotation_variables_clusters.csv', quote=F, row.names=F, col.names=F, sep=',')

save(stclust_stlist, file='stclust_stlist.RData')

ps = STplot(stclust_stlist, samples=samplenames, plot_meta=new_cols, ptsize=2, color_pal=color_pal)

n_plots = names(ps)
write.table(n_plots, 'spagcn_plots.csv', sep=',', row.names = FALSE, col.names=FALSE, quote=FALSE)
for(p in n_plots) {
    saveplot(p, ps[[p]])
}

# Run STdiff to get DEGs and help manual annotation
start_t = Sys.time()
annot_test = unique(gsub(paste0('^', samplenames, '_', collapse='|'), '', names(ps)))
file_list <- list()
for(i in annot_test){
  deg_res = STdiff(stclust_stlist, samples=samplenames, annot=i, topgenes=50, test_type='wilcoxon')
  for(j in names(deg_res)){
    deg_tmp1 = deg_res[[j]] %>% dplyr::arrange(cluster_1, adj_p_val, desc(avg_log2fc)) %>% dplyr::group_by(cluster_1) %>% dplyr::slice_head(n=10) %>% dplyr::ungroup()
    deg_tmp2 = deg_res[[j]] %>% dplyr::filter(adj_p_val < 0.05) %>% dplyr::arrange(cluster_1, adj_p_val, avg_log2fc) %>% dplyr::group_by(cluster_1) %>% dplyr::slice_head(n=10) %>% dplyr::ungroup()
    deg_tmp = rbind(deg_tmp1, deg_tmp2) %>% dplyr::arrange(cluster_1, adj_p_val, desc(avg_log2fc))
    deg_tmp = deg_tmp[!duplicated(deg_tmp), ]
    file_name <- paste0('spagcn_', j, '_', i, '_top_deg')
    write.csv(deg_tmp, paste0(file_name, '.csv'), quote=F, row.names=F)
    file_list <- c(file_list, list(file_name))
    rm(deg_tmp, deg_tmp1, deg_tmp2) # Clean env
  }
}
write.table(file_list, 'spagcn_top_deg.csv',sep=',', row.names = FALSE, col.names=FALSE, quote=FALSE)

end_t = difftime(Sys.time(), start_t, units='min')
cat(paste0('Differential expression analysis completed in ', round(end_t, 2), ' min.'))

